/*******************************************************************************
 * Copyright (c) 2010 Maciej Kaniewski (mk@firegnom.com).
 *  
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 3 of the License, or
 *     (at your option) any later version.
 *  
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *  
 *     You should have received a copy of the GNU General Public License
 *     along with this program; if not, write to the Free Software Foundation,
 *     Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *  
 *     Contributors:
 *      Maciej Kaniewski (mk@firegnom.com) - initial API and implementation
 ******************************************************************************/
package com.firegnom.valkyrie.net.protocol;

// TODO: Auto-generated Javadoc
/**
 * MooDS Class File for Java.
 * 
 * @author Generated by MooDS Generator v2.1.0 - 2006 CNAM, INT, Filao
 */

public class PlayerStats {

	// attributes
	/** The hp. */
	public int hp;
	
	/** The max hp. */
	public int maxHp;
	
	/** The mp. */
	public int mp;
	
	/** The max mp. */
	public int maxMp;
	
	/** The alive. */
	public boolean alive;

	// constructor
	/**
	 * Instantiates a new player stats.
	 */
	public PlayerStats() {
		hp = 0;
		maxHp = 0;
		mp = 0;
		maxMp = 0;
		alive = false;
	}

	// setter/getter methods
	/**
	 * Gets the hp.
	 *
	 * @return the hp
	 */
	public int getHp() {
		return hp;
	}

	/**
	 * Sets the hp.
	 *
	 * @param _local_var the new hp
	 */
	public void setHp(int _local_var) {
		hp = _local_var;
	}

	/**
	 * Gets the max hp.
	 *
	 * @return the max hp
	 */
	public int getMaxHp() {
		return maxHp;
	}

	/**
	 * Sets the max hp.
	 *
	 * @param _local_var the new max hp
	 */
	public void setMaxHp(int _local_var) {
		maxHp = _local_var;
	}

	/**
	 * Gets the mp.
	 *
	 * @return the mp
	 */
	public int getMp() {
		return mp;
	}

	/**
	 * Sets the mp.
	 *
	 * @param _local_var the new mp
	 */
	public void setMp(int _local_var) {
		mp = _local_var;
	}

	/**
	 * Gets the max mp.
	 *
	 * @return the max mp
	 */
	public int getMaxMp() {
		return maxMp;
	}

	/**
	 * Sets the max mp.
	 *
	 * @param _local_var the new max mp
	 */
	public void setMaxMp(int _local_var) {
		maxMp = _local_var;
	}

	/**
	 * Gets the alive.
	 *
	 * @return the alive
	 */
	public boolean getAlive() {
		return alive;
	}

	/**
	 * Sets the alive.
	 *
	 * @param _local_var the new alive
	 */
	public void setAlive(boolean _local_var) {
		alive = _local_var;
	}

}
