/*******************************************************************************
 * Copyright (c) 2010 Maciej Kaniewski (mk@firegnom.com).
 * 
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 * 
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 * 
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software Foundation,
 *    Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 * 
 *    Contributors:
 *     Maciej Kaniewski (mk@firegnom.com) - initial API and implementation
 ******************************************************************************/
package com.firegnom.valkyrie.net.protocol;

// TODO: Auto-generated Javadoc
/**
 * MooDS Class File for Java.
 * 
 * @author Generated by MooDS Generator v2.1.0 - 2006 CNAM, INT, Filao
 */

public class PlayerMove {

	// attributes
	/** The player name. */
	public String playerName;

	/** The player class. */
	public int playerClass;

	/** The path. */
	public Path path;

	// constructor
	/**
	 * Instantiates a new player move.
	 */
	public PlayerMove() {
		playerName = "";
		playerClass = 0;
		path = new Path();
	}

	/**
	 * Gets the path.
	 * 
	 * @return the path
	 */
	public Path getPath() {
		return path;
	}

	/**
	 * Gets the player class.
	 * 
	 * @return the player class
	 */
	public int getPlayerClass() {
		return playerClass;
	}

	// setter/getter methods
	/**
	 * Gets the player name.
	 * 
	 * @return the player name
	 */
	public String getPlayerName() {
		return playerName;
	}

	/**
	 * Sets the path.
	 * 
	 * @param _local_var
	 *            the new path
	 */
	public void setPath(final Path _local_var) {
		path = _local_var;
	}

	/**
	 * Sets the player class.
	 * 
	 * @param _local_var
	 *            the new player class
	 */
	public void setPlayerClass(final int _local_var) {
		playerClass = _local_var;
	}

	/**
	 * Sets the player name.
	 * 
	 * @param _local_var
	 *            the new player name
	 */
	public void setPlayerName(final String _local_var) {
		playerName = _local_var;
	}

}
