/*******************************************************************************
 * Copyright (c) 2010 Maciej Kaniewski (mk@firegnom.com).
 * 
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 * 
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 * 
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software Foundation,
 *    Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 * 
 *    Contributors:
 *     Maciej Kaniewski (mk@firegnom.com) - initial API and implementation
 ******************************************************************************/
package com.firegnom.valkyrie.net.protocol;

// TODO: Auto-generated Javadoc
/**
 * MooDS Class File for Java.
 * 
 * @author Generated by MooDS Generator v2.1.0 - 2006 CNAM, INT, Filao
 */

public class PlayerPositionMessage {

	// attributes
	/** The user name. */
	public String userName;

	/** The player class. */
	public int playerClass;

	/** The x. */
	public short x;

	/** The y. */
	public short y;

	// constructor
	/**
	 * Instantiates a new player position message.
	 */
	public PlayerPositionMessage() {
		userName = "";
		playerClass = 0;
		x = 0;
		y = 0;
	}

	/**
	 * Gets the player class.
	 * 
	 * @return the player class
	 */
	public int getPlayerClass() {
		return playerClass;
	}

	// setter/getter methods
	/**
	 * Gets the user name.
	 * 
	 * @return the user name
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * Gets the x.
	 * 
	 * @return the x
	 */
	public short getX() {
		return x;
	}

	/**
	 * Gets the y.
	 * 
	 * @return the y
	 */
	public short getY() {
		return y;
	}

	/**
	 * Sets the player class.
	 * 
	 * @param _local_var
	 *            the new player class
	 */
	public void setPlayerClass(final int _local_var) {
		playerClass = _local_var;
	}

	/**
	 * Sets the user name.
	 * 
	 * @param _local_var
	 *            the new user name
	 */
	public void setUserName(final String _local_var) {
		userName = _local_var;
	}

	/**
	 * Sets the x.
	 * 
	 * @param _local_var
	 *            the new x
	 */
	public void setX(final short _local_var) {
		x = _local_var;
	}

	/**
	 * Sets the y.
	 * 
	 * @param _local_var
	 *            the new y
	 */
	public void setY(final short _local_var) {
		y = _local_var;
	}

}
